Warehouse/Controllers/AccessController.cs
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Warehouse.Models;
using Microsoft.AspNetCore.Authorization;
using System.Drawing.Text;
using Microsoft.EntityFrameworkCore;
using Warehouse.Data;

namespace Warehouse.Controllers
{
    public class AccessController : Controller
    {

        private readonly SingletonCurrentlyLoggedInUser _singleton;
        private readonly SingletonSum _singletonSummarySum;
        private readonly WarehouseContext _context;

        public AccessController(SingletonCurrentlyLoggedInUser singleton, SingletonSum singletonSummarySum, WarehouseContext context)
        {
            _singleton = singleton;
            _singletonSummarySum = singletonSummarySum;
            _context = context;
        }

        public IActionResult Login()
        {
            _singletonSummarySum.setSums(_context);
            ClaimsPrincipal claimUser = HttpContext.User;
            if (claimUser.Identity.IsAuthenticated)
                return RedirectToAction("Index", "Home");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(VMLogin modelLogin)
        {
            var listOfUsers = _context.VMLogin.Where(p => p.User == modelLogin.User && p.Pwd == modelLogin.Pwd).ToList();

            if (listOfUsers.Count > 0)
            {

                List<Claim> claims = new List<Claim>() {
                    new Claim(ClaimTypes.NameIdentifier, modelLogin.User)
                };

                ClaimsIdentity claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

                AuthenticationProperties properties = new AuthenticationProperties()
                {
                    AllowRefresh = true,
                    IsPersistent = false
                };

                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme,
                    new ClaimsPrincipal(claimsIdentity), properties);

                _singleton.setLogin(modelLogin);
                _singleton.setID(listOfUsers.First().id);
                var idtmp = _singleton.getUserID();
                _singletonSummarySum.setSums(_context);
                return RedirectToAction("Index", "Home");
            }

            ViewData["ValidateMessage"] = "user not found";
            return View();
        }

        public IActionResult CreateUser()
        {
            if (TempData.ContainsKey("unSuccessMessage"))
            {
                ViewData["ValidateMessage"] = TempData["unSuccessMessage"];
            }
            return View();
        }

        [HttpPost]
        public IActionResult CreateUser(VMLogin newUser)
        {
            if (ReadingUsers.AddUser(newUser, _context))
            {
                ViewData["ValidateMessage"] = "successfuly created new user";
                return View();
            }
            TempData["unSuccessMessage"] = "cannot create such user";
            return RedirectToAction("CreateUser");
        }

        public IActionResult DeleteUser()
        {
            ViewBag.wSum = _singletonSummarySum.getWarehouseSum();
            ViewBag.cSum = _singletonSummarySum.getCategoriesSum();
            ViewBag.cIDs = _singletonSummarySum.getCategoriesIDs();
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> DeleteUser(VMLogin login)
        {
            ViewBag.wSum = _singletonSummarySum.getWarehouseSum();
            ViewBag.cSum = _singletonSummarySum.getCategoriesSum();
            ViewBag.cIDs = _singletonSummarySum.getCategoriesIDs();
            var currentUser = _singleton.getLogin();
            ReadingUsers.DeleteUser(currentUser);
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Login", "Access");

        }

        public IActionResult GoToMainPage()
        {
            return RedirectToAction("Index", "Home");
        }

        public IActionResult GoToCreatingUser()
        {
            return RedirectToAction("CreateUser", "Access");
        }

        public IActionResult GoToDeletingUser()
        {
            return RedirectToAction("DeleteUser", "Access");
        }

    }
}

Warehouse/Controllers/VMLoginsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Warehouse.Data;
using Warehouse.Models;

namespace Warehouse.Controllers
{
    public class VMLoginsController : Controller
    {
        private readonly WarehouseContext _context;
        private readonly SingletonSum _singletonSummarySum;
        public VMLoginsController(WarehouseContext context, SingletonSum singletonSummarySum)
        {
            _context = context;
            _singletonSummarySum = singletonSummarySum;
        }

        // GET: VMLogins
        public async Task<IActionResult> Index()
        {
              return _context.VMLogin != null ? 
                          View(await _context.VMLogin.ToListAsync()) :
                          Problem("Entity set 'WarehouseContext.VMLogin'  is null.");
        }

        // GET: VMLogins/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: VMLogins/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,User,Pwd")] VMLogin vMLogin)
        {
            if (ModelState.IsValid)
            {
                var users = _context.VMLogin.ToList();
                if (vMLogin.User == null || vMLogin.User.Length < 3 || vMLogin.Pwd == null || vMLogin.Pwd.Length < 3)
                {
                    ViewData["ValidateMessage"] = "Cannot create such user";
                    return View(vMLogin);
                }
                foreach (var userInUsers in users)
                {
                    if (vMLogin.User == userInUsers.User)
                    {
                        ViewData["ValidateMessage"] = "Cannot create such user";
                        return View(vMLogin);
                    }
                }
                _context.Add(vMLogin);
                await _context.SaveChangesAsync();
                return RedirectToAction("Login","Access");
            }
            return View(vMLogin);
        }

        // GET: VMLogins/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            ViewBag.wSum = _singletonSummarySum.getWarehouseSum();
            ViewBag.cSum = _singletonSummarySum.getCategoriesSum();
            ViewBag.cIDs = _singletonSummarySum.getCategoriesIDs();
            if (id == null || _context.VMLogin == null)
            {
                return NotFound();
            }

            var vMLogin = await _context.VMLogin
                .FirstOrDefaultAsync(m => m.id == id);
            if (vMLogin == null)
            {
                return NotFound();
            }

            return View(vMLogin);
        }

        // POST: VMLogins/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            ViewBag.wSum = _singletonSummarySum.getWarehouseSum();
            ViewBag.cSum = _singletonSummarySum.getCategoriesSum();
            ViewBag.cIDs = _singletonSummarySum.getCategoriesIDs();
            if (_context.VMLogin == null)
            {
                return Problem("Entity set 'WarehouseContext.VMLogin'  is null.");
            }
            var vMLogin = await _context.VMLogin.FindAsync(id);
            if (vMLogin != null)
            {
                _context.VMLogin.Remove(vMLogin);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction("LogOut","Home");
        }

        private bool VMLoginExists(int id)
        {
          return (_context.VMLogin?.Any(e => e.id == id)).GetValueOrDefault();
        }
    }
}

Warehouse/Views/Access/CreateUser.cshtml
@model Warehouse.Models.VMLogin;
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="~/css/boottheme.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Warehouse.styles.css" asp-append-version="true" />
    <title>CreateUser</title>
</head>
<body>
    <div style="padding: 20px; padding-left: 40px">
        <form asp-controller="Access" asp-action="CreateUser" method="post">
            <h1>Create new user</h1>
            <br/>
            <input type="text" placeholder="username" asp-for="User" />
            <input type="password" placeholder="password" asp-for="Pwd" />
            <button class="btn btn-primary" type="submit">Register</button>
            <button class="btn btn-primary" asp-action="GoToMainPage">Back</button>
            @if (ViewData["ValidateMessage"] != null)
            {
                <br />
                <br />
                <label>@ViewData["ValidateMessage"]</label>
            }
        </form>
    </div>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>

</body>
</html>

Warehouse/Views/Access/DeleteUser.cshtml
@model Warehouse.Models.VMLogin
@{
    ViewData["Title"] = "DeleteUser";
}

<h1>Are you sure you want to delete your account?</h1>
<h2>You will be logged out afterwards</h2>
<div>
    <form method="post" asp-controller="Access" asp-action="DeleteUser" style="display:inline-block">
        <button type="submit" class="btn btn-primary">Yes</button>
    </form>
    <button onclick="location.href='@Url.Action("Index", "Home")'" style="display:inline-block" class="btn btn-primary">No</button>
</div>



Warehouse/Views/Access/Login.cshtml
@model Warehouse.Models.VMLogin;
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="~/css/boottheme.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Warehouse.styles.css" asp-append-version="true" />
    <title>Login</title>
</head>
<body>
    <div style="padding: 20px; padding-left: 40px"> 
        <form asp-controller="Access" asp-action="Login" method="post">
            <h1>Login</h1>
            <br />
            <input type="text" placeholder="username" asp-for="User" />
            <input type="password" placeholder="password" asp-for="Pwd" />
            <button type="submit" class="btn btn-primary">Login</button>
            <button asp-controller="VMLogins" asp-action="Create" class="btn btn-primary">Register</button>
            @if (ViewData["ValidateMessage"] != null)
            {
                <br />
                <br />
                <label>@ViewData["ValidateMessage"]</label>
            }
        </form>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>

</body>
</html>