Warehouse/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Warehouse.Data;
using Warehouse.Models;

namespace Warehouse.Controllers
{
    [Authorize]
    public class CategoriesController : Controller
    {
        private readonly WarehouseContext _context;
        private readonly SingletonSum _singletonSummarySum;
        private readonly SingletonCurrentlyLoggedInUser _singleton;


        public CategoriesController(WarehouseContext context, SingletonSum singletonSummarySum, SingletonCurrentlyLoggedInUser singleton)
        {
            _context = context;
            _singletonSummarySum = singletonSummarySum;
            _singleton = singleton;
        }

        // GET: Categories
        public async Task<IActionResult> Index()
        {
            ViewBag.wSum = _singletonSummarySum.getWarehouseSum();
            ViewBag.cSum = _singletonSummarySum.getCategoriesSum();
            ViewBag.cIDs = _singletonSummarySum.getCategoriesIDs();
            ViewBag.uID = _singleton.getUserID();

            return _context.Category != null ? 
                          View(await _context.Category.ToListAsync()) :
                          Problem("Entity set 'WarehouseContext.Category'  is null.");
        }

    }
}

Warehouse/Controllers/NewProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Warehouse.Data;
using Warehouse.Models;

namespace Warehouse.Controllers
{
    [Authorize]
    public class NewProductsController : Controller
    {
        private readonly WarehouseContext _context;

        private readonly SingletonSum _singletonSummarySum;
        private readonly SingletonCurrentlyLoggedInUser _singleton;

        public NewProductsController(WarehouseContext context,  SingletonSum singletonSummarySum, SingletonCurrentlyLoggedInUser singleton)
        {
            _context = context;
            _singletonSummarySum = singletonSummarySum;
            _singleton = singleton;
        }

        // GET: NewProducts
        public async Task<IActionResult> Index()
        {
            ViewBag.wSum = _singletonSummarySum.getWarehouseSum();
            ViewBag.cSum = _singletonSummarySum.getCategoriesSum();
            ViewBag.cIDs = _singletonSummarySum.getCategoriesIDs();
            ViewBag.uID = _singleton.getUserID();

            var warehouseContext = _context.NewProduct.Include(n => n.category);
            return View(await warehouseContext.ToListAsync());
        }

        // GET: NewProducts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.NewProduct == null)
            {
                return NotFound();
            }

            var newProduct = await _context.NewProduct
                .Include(n => n.category)
                .FirstOrDefaultAsync(m => m.id == id);
            if (newProduct == null)
            {
                return NotFound();
            }

            ViewBag.wSum = _singletonSummarySum.getWarehouseSum();
            ViewBag.cSum = _singletonSummarySum.getCategoriesSum();
            ViewBag.cIDs = _singletonSummarySum.getCategoriesIDs();
            ViewBag.uID = _singleton.getUserID();

            return View(newProduct);
        }

        // GET: NewProducts/Create
        public IActionResult Create()
        {
            ViewData["categoryId"] = new SelectList(_context.Category, "id", "name");
            ViewBag.wSum = _singletonSummarySum.getWarehouseSum();
            ViewBag.cSum = _singletonSummarySum.getCategoriesSum();
            ViewBag.cIDs = _singletonSummarySum.getCategoriesIDs();
            ViewBag.uID = _singleton.getUserID();

            return View();
        }

        // POST: NewProducts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,code,name,description,categoryId,quantity,measure,price,Version")] NewProduct newProduct)
        {
            ViewBag.wSum = _singletonSummarySum.getWarehouseSum();
            ViewBag.cSum = _singletonSummarySum.getCategoriesSum();
            ViewBag.cIDs = _singletonSummarySum.getCategoriesIDs();
            ViewBag.uID = _singleton.getUserID();
            if (ModelState.IsValid)
            {
                var list = _context.NewProduct.Where(p => p.code == newProduct.code).ToList();
                if (list.Count > 0)
                {
                    ViewData["ValidateMessage"] = "Such code is already assigned to another product";
                    ViewData["categoryId"] = new SelectList(_context.Category, "id", "name", newProduct.categoryId);
                    return View(newProduct);
                }

                _context.Add(newProduct);
                await _context.SaveChangesAsync();
                _singletonSummarySum.setSums(_context);
                return RedirectToAction(nameof(Index));
            }
            ViewData["categoryId"] = new SelectList(_context.Category, "id", "name", newProduct.categoryId);
            return View(newProduct);
        }

        // GET: NewProducts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.NewProduct == null)
            {
                return NotFound();
            }

            var newProduct = await _context.NewProduct.FindAsync(id);
            if (newProduct == null)
            {
                return NotFound();
            }
            ViewBag.wSum = _singletonSummarySum.getWarehouseSum();
            ViewBag.cSum = _singletonSummarySum.getCategoriesSum();
            ViewBag.cIDs = _singletonSummarySum.getCategoriesIDs();
            ViewBag.uID = _singleton.getUserID();

            ViewData["categoryId"] = new SelectList(_context.Category, "id", "name", newProduct.categoryId);
            return View(newProduct);
        }

        // POST: NewProducts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        //public async Task<IActionResult> Edit(int id, [Bind("id,code,name,description,categoryId,quantity,measure,price,Version")] NewProduct newProduct)
        public async Task<IActionResult> Edit(int? id, byte[] version)
        {

            ViewBag.uID = _singleton.getUserID();

            if (id == null)
            {
                return NotFound();
            }

            var productToUpdate = await _context.NewProduct
                .FirstOrDefaultAsync(p => p.id == id);

            if (productToUpdate == null)
            {
                NewProduct deletedProduct = new NewProduct();
                await TryUpdateModelAsync(deletedProduct);
                ModelState.AddModelError(
                    string.Empty,
                    "Unable to save changes. The product was deleted by another user."
                );
                _singletonSummarySum.setSums(_context);
                ViewBag.wSum = _singletonSummarySum.getWarehouseSum();
                ViewBag.cSum = _singletonSummarySum.getCategoriesSum();
                ViewBag.cIDs = _singletonSummarySum.getCategoriesIDs();
                ViewData["categoryId"] = new SelectList(_context.Category, "id", "name", deletedProduct.categoryId);
                return View(deletedProduct);
            }

            _context.Entry(productToUpdate).Property("Version").OriginalValue = version;

            if (await TryUpdateModelAsync<NewProduct>(
                productToUpdate,
                "",
                p => p.code, p => p.name, p => p.description, p => p.quantity, p => p.price, p => p.measure, p=>p.categoryId
            ))
            {
                try
                {
                    var list = _context.NewProduct.Where(p => p.id != productToUpdate.id).Where(p => p.code == productToUpdate.code).ToList();
                    if (list.Count > 0)
                    {
                        ViewData["ValidateMessage"] = "Such code is already assigned to another product";
                        ViewData["categoryId"] = new SelectList(_context.Category, "id", "name", productToUpdate.categoryId);
                        ViewBag.wSum = _singletonSummarySum.getWarehouseSum();
                        ViewBag.cSum = _singletonSummarySum.getCategoriesSum();
                        ViewBag.cIDs = _singletonSummarySum.getCategoriesIDs();
                        return View(productToUpdate);
                    }

                    await _context.SaveChangesAsync();
                    ViewData["categoryId"] = new SelectList(_context.Category, "id", "name", productToUpdate.categoryId);
                    _singletonSummarySum.setSums(_context);
                    ViewBag.wSum = _singletonSummarySum.getWarehouseSum();
                    ViewBag.cSum = _singletonSummarySum.getCategoriesSum();
                    ViewBag.cIDs = _singletonSummarySum.getCategoriesIDs();
                    return RedirectToAction(nameof(Index));
                }
                catch (DbUpdateConcurrencyException ex)
                {
                    var exceptionEntry = ex.Entries.Single();
                    var clientValues = (NewProduct)exceptionEntry.Entity;
                    var databaseEntry = exceptionEntry.GetDatabaseValues();
                    if (databaseEntry == null)
                    {
                        ModelState.AddModelError(string.Empty,
                            "Unable to save changes. The product was deleted by another user.");
                    }
                    else
                    {
                        var databaseValues = (NewProduct)databaseEntry.ToObject();

                        if (databaseValues.code != clientValues.code)
                        {
                            ModelState.AddModelError("Code", $"Current value: {databaseValues.code}");
                        }

                        if (databaseValues.name != clientValues.name)
                        {
                            ModelState.AddModelError("Name", $"Current value: {databaseValues.name}");
                        }

                        if (databaseValues.description != clientValues.description)
                        {
                            ModelState.AddModelError("Description", $"Current value: {databaseValues.description}");
                        }

                        if (databaseValues.categoryId != clientValues.categoryId)
                        {

Warehouse/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Warehouse</title>
    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />*@
    <link rel="stylesheet" href="~/css/boottheme.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Warehouse.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Warehouse</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="NewProducts" asp-action="Index">Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="Index">Categories</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" href="/VMLogins/Delete/@ViewBag.uID">Delete Account</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="LogOut">Log Out</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <br />
    <div>
        <div style="margin: 20px">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>

        <div style="margin-top: 100px; margin-left: 20px">
            Total Warehouse Price: @ViewBag.wSum
            <br/>
            Categories Prices:
            <ul>
                @for (int i = 0; i < ViewBag.cSum.Count; i++)
                {
                    <li>@ViewBag.cIDs[i] price: @ViewBag.cSum[i]</li>
                }
            </ul>
        </div>
    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    @*<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>*@
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>